
# Site settings
title: Death Machine Snowboards
email: dave@deathmachinesnowboards.com
description: Super Happytime Death Machine brand makes snowboards and softgoods

source: ./
destination: ./dist

#timezone: America/New_York
baseurl: "" 
url: "https://deathmachinesnowboards.com" # the base hostname & protocol for your site

twitter_username: shdmsnowboards
github_username:  deathmachinesnow

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
    sass_dir: ./_sass

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  -
    scope:
      path: _posts
    values:
      layout: article